
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ssrfjakurvpcshbesvyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNzcmZqYWt1cnZwY3NoYmVzdnlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NDEzMTMsImV4cCI6MjA2MTUxNzMxM30.bIXSMU37FC_Q8xjYodSTARBF_izCeD9_HCk_Tgn-wNQ";

// Performance optimizations for the Supabase client
const clientOptions = {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: typeof window !== 'undefined' ? localStorage : undefined
  },
  global: {
    // Disable real-time subscriptions by default to reduce connection overhead
    realtime: false
  },
  // Add request timeout to prevent hanging requests
  db: {
    schema: 'public'
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, clientOptions);

// Helper function to check if a Supabase response contains an error
export function hasError(response: any): boolean {
  return response && response.error !== undefined;
}

// Helper function to safely access data from a Supabase response
export function safeData<T>(response: any, defaultValue: T): T {
  if (hasError(response) || !response || response.data === undefined || response.data === null) {
    return defaultValue;
  }
  return response.data as T;
}

// Type guard to narrow down a response to data-only (no error)
export function isDataResponse<T>(response: any): response is { data: T; error: null } {
  return !hasError(response) && response?.data !== null && response?.data !== undefined;
}

// Helper to safely get a field from potential error responses
export function safeField<T, K extends keyof T>(obj: T | any, field: K, defaultValue: T[K]): T[K] {
  if (!obj || typeof obj !== 'object' || hasError(obj)) {
    return defaultValue;
  }
  return (obj as T)[field] !== undefined ? (obj as T)[field] : defaultValue;
}

// Helper to cast data safely to a specific type (useful for Supabase tables)
export function castData<T>(data: any): T {
  if (!data) return {} as T;
  return data as T;
}

// Improved type-safe filter function that works better with TypeScript
export function filterByField<T extends keyof Database['public']['Tables']>(
  table: T,
  field: keyof Database['public']['Tables'][T]['Row'] | string,
  value: any
) {
  return supabase
    .from(table)
    .eq(field as string, value);
}

// Safely cast ordered data to the expected type
export function castOrderedData<T>(data: any): T[] {
  if (!data || !Array.isArray(data)) return [] as T[];
  return data as T[];
}

// Type-safe insert function for Supabase tables
export async function typeSafeInsert<T extends keyof Database['public']['Tables']>(
  table: T,
  data: Database['public']['Tables'][T]['Insert']
) {
  return await supabase.from(table).insert(data);
}

// Type-safe update function for Supabase tables
export async function typeSafeUpdate<T extends keyof Database['public']['Tables']>(
  table: T,
  data: Database['public']['Tables'][T]['Update'],
  field: string,
  value: any
) {
  return await supabase.from(table).update(data).eq(field, value);
}
